# Generated by Django 3.2.9 on 2021-12-14 13:30

import app.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='predited_img',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/', validators=[app.validators.validate_file_size]),
        ),
    ]
