# Generated by Django 3.2.9 on 2022-01-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_img_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor_detials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip_addr', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
