# Generated by Django 3.2.9 on 2021-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_img_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='predited_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
