# Generated by Django 4.0.1 on 2022-01-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_visitor_detials'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_detials',
            name='remote_host',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor_detials',
            name='server_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitor_detials',
            name='server_port',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
